### ISSUE TITLE
Plugin "HeadHunter RPG System" Not Working At All

### ISSUE THREAD

**Issue by KGKhan1** [alexsatellite/HeadHunter#1]
Hello,

I recently purchased & installed the plugin you made called "HeadHunter RPG System". However, nothing works. The plugin isn't even shown in the /plugin list. My host says there must be an internal error going on, and I would likely have to contact you to fix this issue. How can this be fixed?

Thank you.

**Comment by alexsatellite** [comment]
Do you have all the dependencies installed? HeadHunter also needs my plugin Helix to work. You can find in the bottom of the HeadHunter overview page.

**Comment by alexsatellite** [comment]
Also you have to give the your start up  error because I'm not a fortune teller :P
