### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by raccoman** [alexsatellite/HeadHunter#12]
When i try to change the name of the gui of /hh command so &4&lHeadHunter to another thing like &c&lHeads, this make a dupe glitch when player close that gui the receive 1 of all heads in the gui! Please fix this shit

**Comment by alexsatellite** [comment]
I think I replied you in spigot, the issue is that you have the same gui name as the sell-heasd gui by default. Use other name.

**Comment by raccoman** [comment]
Hi there is another bug, in the reward of ranking only execute 1 command

**Comment by raccoman** [comment]
Can you please send your discord ID?

**Comment by alexsatellite** [comment]
yes, ByteMagic#4022
