### ISSUE TITLE
Sell heads on current level

### ISSUE THREAD

**Issue by ChrJungbluth** [alexsatellite/HeadHunter#14]
Hi,

i was wondering if it is possible that a player only can sell heads of his current level to gain xp. Every other head should just be sold for money. Great plugin so far :)

If the wanted feature isn´t in place all ready and i just missed to configure it right, would it be possible to get this feature as a paid change?

Best regards

**Comment by alexsatellite** [comment]
i'll check the sell skull system and meanwhile I'll add this along other features.
