### ISSUE TITLE
HeadHunting progress resets when resetting aSkyblock skyblock island.

### ISSUE THREAD

**Issue by dotvb** [alexsatellite/HeadHunter#17]
Is there a way to do this?

**Comment by dotvb** [comment]
Also, is there a way to reset someone's progress in-game via command? Better than deleting their files manually.

**Comment by alexsatellite** [comment]
I'll add a command for that.

**Comment by dotvb** [comment]
Perhaps also a hook for SuperiorSkyblock2 by Omer to reset headhunting progress when resetting your island. I no longer use aSkyblock as it’s old now.
