### ISSUE TITLE
Make this setting work as intended...

### ISSUE THREAD

**Issue by dotvb** [alexsatellite/HeadHunter#19]
"GIVE_XP_ANY_UNLOCKED_MOB"

When set to"false" you can still sell previously unlocked mobs for XP on newer/current mob rank. It should be when set to false you cannot gain HeadHunter XP from previous mobs, only sell their heads for money.

**Comment by ChromeOG** [comment]
hi, do you have the cofig file? im not getting it from the .jar

**Comment by dotvb** [comment]
It’s in headhunter_hconf folder. The config is named instance.

**Comment by ChromeOG** [comment]
THANK YOU!!!

**Comment by ChromeOG** [comment]
btw, I totally agreed on this issue, BUMP

**Comment by alexsatellite** [comment]
I'll check that again. Maybe I did something wrong in the recode of this feature. Thanks for reporting

**Comment by luststarmc** [comment]
I have the same issue as well...
