### ISSUE TITLE
Some Questions About The Plugin "HHRPGS"

### ISSUE THREAD

**Issue by KGKhan1** [alexsatellite/HeadHunter#2]
Hi,

I have two questions based on the plugin "HeadHunter RPG System". 

1) How can you access the spawner shop (if there is one)?
2) Is there a way I can allow everyone to be able to gain heads by killing any type of mob? (e.g. rank 1 players can kill & receive IG heads.)

**Comment by alexsatellite** [comment]
For creating the shop signs you have to out in the first line of the sign:
[HeadHunter] and in the second line you out the name of the mob.
Example:
[HeadHunter]
wolf

About your second question. Yes you can configure so the plugin doesn't check for levels when you kill a mob. I can't check the name of the parameter now because I'm on the phone. Once I get back I'll reply again.

**Comment by KGKhan1** [comment]
Okay, but Is there like a GUI shop that sells the spawners based on the player’s level?

**Comment by KGKhan1** [comment]
Hi, also, how can I change the lore of the heads? I changed the prices of the heads but the lore still says the original price.

**Comment by alexsatellite** [comment]
You can only change the lore of player skulls at the moment, soon you'll be able to change any lore.

If you want to be able to get any mob head set this in your config instance:
SKULL_NEED_SAMELEVEL: false

**Comment by KGKhan1** [comment]
Okay, and where is the config? I don't see any world or similar to the word: config

**Comment by KGKhan1** [comment]
Also, when will I be able to change the lore for everything?

**Comment by KGKhan1** [comment]
Hm... You here?

**Comment by KGKhan1** [comment]
He...llo? IK I'm being impatient here but you haven't replied in 2 days.

**Comment by alexsatellite** [comment]
Maybe it's time to start reading the overview page to understand the plugin. The config is the instance.json file inside of the HeadHunter_hconf folder.

**Comment by KGKhan1** [comment]
Okay, please also make it so you can change both the lore and the name of any item.

**Comment by KGKhan1** [comment]
Also I changed the GUI name (HeadHunters) in the config but nothing changed.
