### ISSUE TITLE
IG Mask in default config is wrong.

### ISSUE THREAD

**Issue by EvilSlime** [alexsatellite/HeadHunter#3]
It should be this.  
IRON_GOLEM:
    1:
      Heads_needed: 128
      Previous_Masks_needed: 0
      Effects:
         - "ExtraHeartEffect:@Amount:4"
         - "PermanentPotionEffect:@Effects:SLOW(1)"
    2:
      Heads_needed: 320
      Previous_Masks_needed: 1
      Effects:
         - "ExtraHeartEffect:@Amount:6"
         - "PermanentPotionEffect:@Effects:SLOW(1)"
    3:
      Heads_needed: 640
      Previous_Masks_needed: 1
      Effects:
         - "ExtraHeartEffect:@Amount:8"
         - "PermanentPotionEffect:@Effects:SLOW(2)"
    4:
      Heads_needed: 1280
      Previous_Masks_needed: 1
      Effects:
         - "ExtraHeartEffect:@Amount:10"
         - "PermanentPotionEffect:@Effects:SLOW(2)"
    5:
      Heads_needed: 2304
      Previous_Masks_needed: 1
      Effects:
         - "ExtraHeartEffect:@Amount:12"
         - "PermanentPotionEffect:@Effects:SLOW(2)"

**Comment by alexsatellite** [comment]
Fixed
