### ISSUE TITLE
HHRPGS Head Multiplier And Drop Chances

### ISSUE THREAD

**Issue by KGKhan1** [alexsatellite/HeadHunter#5]
Hi,

I'm having some issues using the plugin 'HHPRGS'. The problem is that EVERY time I kill a mob, it always drops two of its heads. How can this be fixed?

Thanks.

**Comment by KGKhan1** [comment]
Are you thinking of replying...?

**Comment by alexsatellite** [comment]
I can reply but I can not check or fix until Sunday.

**Comment by alexsatellite** [comment]
Are you using the mask that give you extra heads?

**Comment by KGKhan1** [comment]
Nope, everyone gets 2 heads every time

**Comment by alexsatellite** [comment]
I get 1 head drop as supposed to be. Make sure that your "extra" head drop doesb't come other plugin.
