### ISSUE TITLE
1.12.2?

### ISSUE THREAD

**Issue by IsThatToasted** [alexsatellite/HeadHunter#8]
Just curious if this is compatible with 1.12.2 or just 1.12? Because honestly i'd like to invest into your work, but i'd rather not waste $11 either.

**Comment by alexsatellite** [comment]
1.12.2 is compatible too, 1.13 isn't

**Comment by IsThatToasted** [comment]
Sounds good, I'll give it a go later this evening. To be straight up with you I've downloaded this plugin elsewhere but have had no luck. That's why I wanted to clarify that it is in fact compatible.
